version: '3.7'

services:
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./recording:/app
      - ./vol:/vol
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

volumes:
  db-data:
